/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIAdmin;

import DAO.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import Entity.*;
import Utils.*;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dantr
 */
public class ProductSearchJFrame extends javax.swing.JFrame {
	
	/**
	 * Creates new form ProductSearchJFrame
	 */
	DefaultTableModel model;
	TypeProductDAO typeDao = new TypeProductDAO();
	ProductDAO dao = new ProductDAO();
	int row = -1;
	private JFileChooser fileChooser;
	public ProductSearchJFrame() {
		initComponents();
		init();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                tabProduct = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                lbImage = new javax.swing.JLabel();
                txtIDProduct = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                txtProductName = new javax.swing.JTextField();
                txtPrice = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                cboType = new javax.swing.JComboBox<>();
                jScrollPane2 = new javax.swing.JScrollPane();
                txtDescription = new javax.swing.JTextArea();
                btnNew = new javax.swing.JButton();
                btnAdd = new javax.swing.JButton();
                btnUpdate = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                tabList = new javax.swing.JPanel();
                btnShowAll = new javax.swing.JButton();
                cboType1 = new javax.swing.JComboBox<>();
                txtSearch = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblSearchProduct = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
                jTabbedPane1.setOpaque(true);

                tabProduct.setBackground(new java.awt.Color(255, 255, 255));

                jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanel2.setToolTipText("");
                jPanel2.setMaximumSize(new java.awt.Dimension(130, 139));
                jPanel2.setMinimumSize(new java.awt.Dimension(130, 139));

                lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khoaitaychien.jpg"))); // NOI18N
                lbImage.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbImageMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                txtIDProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtIDProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtIDProduct.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtIDProductActionPerformed(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setText("ID Product:");

                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel5.setText("Product Name:");

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel6.setText("Type:");

                jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel7.setText("Price:");

                txtProductName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtProductName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtProductName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtProductNameActionPerformed(evt);
                        }
                });

                txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtPrice.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtPriceActionPerformed(evt);
                        }
                });

                jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel8.setText("Description");

                cboType.setBackground(new java.awt.Color(255, 255, 255));
                cboType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                cboType.setForeground(new java.awt.Color(255, 153, 255));
                cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                cboType.setBorder(null);
                cboType.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cboTypeActionPerformed(evt);
                        }
                });

                txtDescription.setColumns(20);
                txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtDescription.setRows(5);
                txtDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtDescription.setOpaque(false);
                jScrollPane2.setViewportView(txtDescription);

                btnNew.setBackground(new java.awt.Color(255, 153, 255));
                btnNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnNew.setForeground(new java.awt.Color(255, 255, 255));
                btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sale (2).png"))); // NOI18N
                btnNew.setText("NEW");
                btnNew.setMaximumSize(new java.awt.Dimension(111, 51));
                btnNew.setMinimumSize(new java.awt.Dimension(111, 51));
                btnNew.setPreferredSize(new java.awt.Dimension(111, 51));
                btnNew.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNewActionPerformed(evt);
                        }
                });

                btnAdd.setBackground(new java.awt.Color(255, 153, 255));
                btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnAdd.setForeground(new java.awt.Color(255, 255, 255));
                btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plus.png"))); // NOI18N
                btnAdd.setText("ADD");
                btnAdd.setMaximumSize(new java.awt.Dimension(111, 51));
                btnAdd.setMinimumSize(new java.awt.Dimension(111, 51));
                btnAdd.setPreferredSize(new java.awt.Dimension(111, 51));
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnUpdate.setBackground(new java.awt.Color(255, 153, 255));
                btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
                btnUpdate.setText("UPDATE");
                btnUpdate.setMaximumSize(new java.awt.Dimension(111, 51));
                btnUpdate.setMinimumSize(new java.awt.Dimension(111, 51));
                btnUpdate.setPreferredSize(new java.awt.Dimension(111, 51));
                btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUpdateActionPerformed(evt);
                        }
                });

                btnDelete.setBackground(new java.awt.Color(255, 153, 255));
                btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnDelete.setForeground(new java.awt.Color(255, 255, 255));
                btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
                btnDelete.setText("DELETE");
                btnDelete.setMaximumSize(new java.awt.Dimension(111, 51));
                btnDelete.setMinimumSize(new java.awt.Dimension(111, 51));
                btnDelete.setPreferredSize(new java.awt.Dimension(111, 51));
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout tabProductLayout = new javax.swing.GroupLayout(tabProduct);
                tabProduct.setLayout(tabProductLayout);
                tabProductLayout.setHorizontalGroup(
                        tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabProductLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProductLayout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(tabProductLayout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtIDProduct)
                                                        .addGroup(tabProductLayout.createSequentialGroup()
                                                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel5))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(txtProductName)
                                                        .addComponent(cboType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtPrice)))
                                        .addGroup(tabProductLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                tabProductLayout.setVerticalGroup(
                        tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabProductLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tabProductLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtIDProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6)
                                                .addGap(9, 9, 9)
                                                .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Product", tabProduct);

                tabList.setBackground(new java.awt.Color(255, 255, 255));

                btnShowAll.setBackground(new java.awt.Color(255, 153, 255));
                btnShowAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnShowAll.setForeground(new java.awt.Color(255, 255, 255));
                btnShowAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/List (2).png"))); // NOI18N
                btnShowAll.setText("Show All");
                btnShowAll.setMaximumSize(new java.awt.Dimension(111, 51));
                btnShowAll.setMinimumSize(new java.awt.Dimension(111, 51));
                btnShowAll.setPreferredSize(new java.awt.Dimension(111, 51));
                btnShowAll.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnShowAllActionPerformed(evt);
                        }
                });

                cboType1.setBackground(new java.awt.Color(255, 255, 255));
                cboType1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                cboType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                cboType1.setOpaque(true);

                txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtSearchActionPerformed(evt);
                        }
                });
                txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtSearchKeyReleased(evt);
                        }
                });

                tblSearchProduct.setBackground(new java.awt.Color(255, 255, 255));
                tblSearchProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                tblSearchProduct.setForeground(new java.awt.Color(255, 102, 255));
                tblSearchProduct.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null}
                        },
                        new String [] {
                                "IDProduct", "ProductName", "Type", "Price", "Description"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tblSearchProduct.setRowHeight(25);
                tblSearchProduct.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblSearchProductMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tblSearchProduct);
                if (tblSearchProduct.getColumnModel().getColumnCount() > 0) {
                        tblSearchProduct.getColumnModel().getColumn(0).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(0).setPreferredWidth(10);
                        tblSearchProduct.getColumnModel().getColumn(1).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(1).setPreferredWidth(20);
                        tblSearchProduct.getColumnModel().getColumn(2).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(2).setPreferredWidth(10);
                        tblSearchProduct.getColumnModel().getColumn(3).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(3).setPreferredWidth(20);
                        tblSearchProduct.getColumnModel().getColumn(4).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(4).setPreferredWidth(40);
                }

                javax.swing.GroupLayout tabListLayout = new javax.swing.GroupLayout(tabList);
                tabList.setLayout(tabListLayout);
                tabListLayout.setHorizontalGroup(
                        tabListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabListLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboType1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                );
                tabListLayout.setVerticalGroup(
                        tabListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabListLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tabListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cboType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                jTabbedPane1.addTab("List", tabList);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtProductNameActionPerformed

        private void txtIDProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProductActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtIDProductActionPerformed

        private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtPriceActionPerformed

    private void cboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTypeActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_cboTypeActionPerformed

        private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
                // TODO add your handling code here:
                searchProduct();
        }//GEN-LAST:event_txtSearchKeyReleased

        private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
                // TODO add your handling code here:
                searchProduct();
        }//GEN-LAST:event_txtSearchActionPerformed

        private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
                // TODO add your handling code here:
		clearFrom();
                
        }//GEN-LAST:event_btnNewActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                // TODO add your handling code here:
		insert();
        }//GEN-LAST:event_btnAddActionPerformed

        private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnUpdateActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnDeleteActionPerformed

        private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
                // TODO add your handling code here:
		fillToTable();
        }//GEN-LAST:event_btnShowAllActionPerformed

        private void tblSearchProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchProductMouseClicked
                // TODO add your handling code here:
		if (evt.getClickCount() == 2) {
			this.row = tblSearchProduct.getSelectedRow();
			edit();
			updateStaTus();
		}
		
        }//GEN-LAST:event_tblSearchProductMouseClicked

        private void lbImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImageMouseClicked
                // TODO add your handling code here:
		setProductImage();
        }//GEN-LAST:event_lbImageMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProductSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProductSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProductSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProductSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ProductSearchJFrame().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnNew;
        private javax.swing.JButton btnShowAll;
        private javax.swing.JButton btnUpdate;
        private javax.swing.JComboBox<String> cboType;
        private javax.swing.JComboBox<String> cboType1;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JLabel lbImage;
        private javax.swing.JPanel tabList;
        private javax.swing.JPanel tabProduct;
        private javax.swing.JTable tblSearchProduct;
        private javax.swing.JTextArea txtDescription;
        private javax.swing.JTextField txtIDProduct;
        private javax.swing.JTextField txtPrice;
        private javax.swing.JTextField txtProductName;
        private javax.swing.JTextField txtSearch;
        // End of variables declaration//GEN-END:variables

	private void init() {
		
		this.setLocationRelativeTo(null);
		fillCboType();
		this.fileChooser = new JFileChooser();
		this.model = (DefaultTableModel) this.tblSearchProduct.getModel();
		fillToTable();
		//Để cbo có thể fill theo ProductType lên table
		cboType1.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent event) {
				if (event.getStateChange() == ItemEvent.SELECTED) {
					fillToTableCbo();
					
					

				}
			}

		});
		
		updateStaTus();
	}
	
	//Lấy dữ liệu từ form để chuyển thành product
	private Product getForm(){
		Product pd = new Product();
		pd.setIdProduct(txtIDProduct.getText());
		pd.setProductName(txtProductName.getText());
		ProductType pdt = (ProductType) this.cboType.getSelectedItem();
		pd.setTypePro(pdt.getIDType().toString());
		pd.setPrice(Double.valueOf(this.txtPrice.getText()).doubleValue());
		pd.setDescreption(txtDescription.getText());
		pd.setImage(this.lbImage.getToolTipText());
		return pd;
		
	}
	
	//hàm thêm product
	private void insert(){
		Product model = this.getForm();
		try {
				this.dao.insert(model);
				fillToTable();
				clearFrom();
				MsgBox.alert(this, "Thêm mới thành công!");
			} catch (Exception e) {
				System.out.println(e);
				MsgBox.alert(this, "Thêm mới thất bại!");
			}
		
	}
	
	//lấy dữ liệu từ Product để đưa lên form
	private void setForm(Product pd) {
		this.txtIDProduct.setText(pd.getIdProduct());
		this.txtProductName.setText(pd.getProductName());
		this.txtPrice.setText(String.valueOf(pd.getPrice()));
		//lấy id từ product để thêm fill lên cbo
		DefaultComboBoxModel<ProductType> model = (DefaultComboBoxModel) this.cboType.getModel();
		model.removeAllElements();
		model.addElement(this.typeDao.selectById(pd.getTypePro()));
		this.cboType.setSelectedItem(this.typeDao.selectById(pd.getTypePro()));
		this.txtDescription.setText(pd.getDescreption());
		if (pd.getImage()!= null) {
			this.lbImage.setToolTipText(pd.getImage());
			this.lbImage.setIcon(XImage.read(pd.getImage()));
		}
	}
	
	
	//Chỉnh lại trật tự Jframe
	private void updateStaTus(){
		boolean edit = (this.row >= 0);
		this.btnAdd.setEnabled(!edit);
		this.btnUpdate.setEnabled(edit);
		this.btnDelete.setEnabled(edit);
	}
	
	
	
	//hàm edit
	private void edit(){
		String pdid = (String) this.tblSearchProduct.getValueAt(this.row, 0);
		Product cd = this.dao.selectById(pdid);

		setForm(cd);
		//updateStatus();
		this.jTabbedPane1.setSelectedIndex(0);
	}
	
	
	
	
	//Đẩy dữ liệu từ table ProductType vô CBo
	private void fillCboType() {
		//Cbo bên form
		DefaultComboBoxModel<ProductType> model = (DefaultComboBoxModel) this.cboType.getModel();
		//Cbo bên List
		DefaultComboBoxModel<ProductType> model1 = (DefaultComboBoxModel) this.cboType1.getModel();
		model.removeAllElements();
		model1.removeAllElements();
		List<ProductType> list = this.typeDao.selectAll();

		for (ProductType pd : list) {
					model.addElement(pd);
					model1.addElement(pd);
		}
		
	}
	//Fill dữ liệu lên table theo ProductTyoe của cbo
	private void fillToTableCbo(){
		ProductType pt = (ProductType) this.cboType1.getSelectedItem();
		model.setRowCount(0);
		try {
			List<Product> list = this.dao.selectByType(pt.getIDType());
			for (Product pd : list) {
				Object[] row = {pd.getIdProduct(), pd.getProductName(), pd.getTypePro(), Double.valueOf(pd.getPrice()), pd.getDescreption()};
				model.addRow(row);
				
			}
			tblSearchProduct.setModel(model);
		} catch (Exception e) {
			MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
		}
	}
	
	
	//Fill toàn bộ dữ liệu lên table
	private void fillToTable(){
		model.setRowCount(0);
		try {
			List<Product> list = this.dao.selectAll();
			for (Product pd : list) {
				Object[] row = {pd.getIdProduct(), pd.getProductName(), pd.getTypePro(), Double.valueOf(pd.getPrice()), pd.getDescreption()};
				model.addRow(row);
				
			}
			tblSearchProduct.setModel(model);
		} catch (Exception e) {
			MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
		}
	}
	
	
	//Tìm kiếm sản phẩm dựa vào ID,Tên,Giá
	private void searchProduct() {
		//Lấy giá trị từ textf
		String search = txtSearch.getText();
		double num;
		//Chuyển String thành số để sql ko bị lỗi
		try {
			num = Double.parseDouble(search);
		} catch (Exception e) {
			num = 0;
		}
		model.setRowCount(0);
		//Excus câu lệnh sql
		try {
			List<Product> list = this.dao.searchSQL(search, num);
			for (Product pd : list) {
				Object[] row = {pd.getIdProduct(), pd.getProductName(), pd.getTypePro(), Double.valueOf(pd.getPrice()), pd.getDescreption()};
				model.addRow(row);
			}
			tblSearchProduct.setModel(model);

		} catch (Exception e) {
			MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
		}
		
	}
	
	//ClearFrom
	private void clearFrom(){
		Product pd = new Product();
		setForm(pd);
		this.row = -1;
			
		fillCboType();
		updateStaTus();
	}
	//Chon Anh cho product
	private void setProductImage() {
		if (this.fileChooser.showOpenDialog(this) == 0) {
			File file = this.fileChooser.getSelectedFile();
			XImage.save(file);
			ImageIcon icon = XImage.read(file.getName());
			this.lbImage.setIcon(icon);
			this.lbImage.setToolTipText(file.getName());
		}
	}
	
}
