/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIAdmin;

import DAO.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import Entity.*;
import Utils.*;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dantr
 */
public class ProductSearchJFrame extends javax.swing.JFrame {
	
	/**
	 * Creates new form ProductSearchJFrame
	 */
	DefaultTableModel model;
	TypeProductDAO typeDao = new TypeProductDAO();
	ProductDAO dao = new ProductDAO();

	public ProductSearchJFrame() {
		initComponents();
		init();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                tabProduct = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                lbImage = new javax.swing.JLabel();
                txtIDProduct = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                btnUpdate = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                txtProductName = new javax.swing.JTextField();
                txtPrice = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                cboType = new javax.swing.JComboBox<>();
                btnAdd = new javax.swing.JButton();
                btnNew = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                txtDescription = new javax.swing.JTextArea();
                tabList = new javax.swing.JPanel();
                cboType1 = new javax.swing.JComboBox<>();
                txtSearch = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblSearchProduct = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
                jTabbedPane1.setOpaque(true);

                tabProduct.setBackground(new java.awt.Color(255, 255, 255));

                jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanel2.setToolTipText("");
                jPanel2.setMaximumSize(new java.awt.Dimension(130, 139));
                jPanel2.setMinimumSize(new java.awt.Dimension(130, 139));

                lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khoaitaychien.jpg"))); // NOI18N

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                txtIDProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtIDProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtIDProduct.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtIDProductActionPerformed(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setText("ID Product:");

                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel5.setText("Product Name:");

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel6.setText("Type:");

                jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel7.setText("Price:");

                btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
                btnUpdate.setText("UPDATE");

                btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
                btnDelete.setText("DELETE");

                txtProductName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtProductName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtProductName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtProductNameActionPerformed(evt);
                        }
                });

                txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtPrice.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtPriceActionPerformed(evt);
                        }
                });

                jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel8.setText("Description");

                cboType.setBackground(new java.awt.Color(255, 255, 255));
                cboType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                cboType.setForeground(new java.awt.Color(255, 153, 255));
                cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                cboType.setBorder(null);
                cboType.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cboTypeActionPerformed(evt);
                        }
                });

                btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnAdd.setText("ADD");

                btnNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnNew.setText("NEW");

                txtDescription.setColumns(20);
                txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtDescription.setRows(5);
                txtDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtDescription.setOpaque(false);
                jScrollPane2.setViewportView(txtDescription);

                javax.swing.GroupLayout tabProductLayout = new javax.swing.GroupLayout(tabProduct);
                tabProduct.setLayout(tabProductLayout);
                tabProductLayout.setHorizontalGroup(
                        tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabProductLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProductLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpdate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(tabProductLayout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtIDProduct)
                                                        .addGroup(tabProductLayout.createSequentialGroup()
                                                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel5))
                                                                .addGap(0, 281, Short.MAX_VALUE))
                                                        .addComponent(txtProductName)
                                                        .addComponent(cboType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtPrice)))
                                        .addGroup(tabProductLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                tabProductLayout.setVerticalGroup(
                        tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabProductLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tabProductLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtIDProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6)
                                                .addGap(9, 9, 9)
                                                .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Product", tabProduct);

                tabList.setBackground(new java.awt.Color(255, 255, 255));

                cboType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(179, 0, 134)));
                txtSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtSearchActionPerformed(evt);
                        }
                });
                txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtSearchKeyReleased(evt);
                        }
                });

                tblSearchProduct.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null}
                        },
                        new String [] {
                                "IDProduct", "ProductName", "Type", "Price", "Description"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tblSearchProduct.setRowHeight(25);
                jScrollPane1.setViewportView(tblSearchProduct);
                if (tblSearchProduct.getColumnModel().getColumnCount() > 0) {
                        tblSearchProduct.getColumnModel().getColumn(0).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(0).setPreferredWidth(10);
                        tblSearchProduct.getColumnModel().getColumn(1).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(1).setPreferredWidth(20);
                        tblSearchProduct.getColumnModel().getColumn(2).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(2).setPreferredWidth(10);
                        tblSearchProduct.getColumnModel().getColumn(3).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(3).setPreferredWidth(20);
                        tblSearchProduct.getColumnModel().getColumn(4).setResizable(false);
                        tblSearchProduct.getColumnModel().getColumn(4).setPreferredWidth(40);
                }

                javax.swing.GroupLayout tabListLayout = new javax.swing.GroupLayout(tabList);
                tabList.setLayout(tabListLayout);
                tabListLayout.setHorizontalGroup(
                        tabListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabListLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboType1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                );
                tabListLayout.setVerticalGroup(
                        tabListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabListLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tabListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cboType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                jTabbedPane1.addTab("List", tabList);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtProductNameActionPerformed

        private void txtIDProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProductActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtIDProductActionPerformed

        private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtPriceActionPerformed

    private void cboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTypeActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_cboTypeActionPerformed

        private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
                // TODO add your handling code here:
                searchProduct();
        }//GEN-LAST:event_txtSearchKeyReleased

        private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
                // TODO add your handling code here:
                searchProduct();
        }//GEN-LAST:event_txtSearchActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProductSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProductSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProductSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProductSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ProductSearchJFrame().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnNew;
        private javax.swing.JButton btnUpdate;
        private javax.swing.JComboBox<String> cboType;
        private javax.swing.JComboBox<String> cboType1;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JLabel lbImage;
        private javax.swing.JPanel tabList;
        private javax.swing.JPanel tabProduct;
        private javax.swing.JTable tblSearchProduct;
        private javax.swing.JTextArea txtDescription;
        private javax.swing.JTextField txtIDProduct;
        private javax.swing.JTextField txtPrice;
        private javax.swing.JTextField txtProductName;
        private javax.swing.JTextField txtSearch;
        // End of variables declaration//GEN-END:variables

	private void init() {
		
		this.setLocationRelativeTo(null);
		fillCboType();
		this.model = (DefaultTableModel) this.tblSearchProduct.getModel();
		fillToTable();
	}

	private void fillCboType() {
		DefaultComboBoxModel<ProductType> model = (DefaultComboBoxModel) this.cboType.getModel();
		DefaultComboBoxModel<ProductType> model1 = (DefaultComboBoxModel) this.cboType1.getModel();
		model.removeAllElements();
		model1.removeAllElements();
		List<ProductType> list = this.typeDao.selectAll();

		for (ProductType pd : list) {
					model.addElement(pd);
					model1.addElement(pd);
		}
	}

	private void fillToTable(){
		model.setRowCount(0);
		try {
			List<Product> list = this.dao.selectAll();
			for (Product pd : list) {
				Object[] row = {pd.getIdProduct(), pd.getProductName(), pd.getTypePro(), Double.valueOf(pd.getPrice()), pd.getDescreption()};
				model.addRow(row);
				
			}
			tblSearchProduct.setModel(model);
		} catch (Exception e) {
			MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
		}
	}

	private void searchProduct() {
		String search = txtSearch.getText();
		double num;
		try {
			num = Double.parseDouble(search);
		} catch (Exception e) {
			num = 0;
		}
		System.out.println(num);
		model.setRowCount(0);
		try {
			List<Product> list = this.dao.searchSQL(search, num);
			for (Product pd : list) {
				Object[] row = {pd.getIdProduct(), pd.getProductName(), pd.getTypePro(), Double.valueOf(pd.getPrice()), pd.getDescreption()};
				model.addRow(row);
			}
			tblSearchProduct.setModel(model);

		} catch (Exception e) {
			MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
		}
		
	}
	
}
