/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIAdmin;

import DAO.PromotionDAO;
import Entity.Account;
import Entity.Promotions;
import Utils.MsgBox;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import Utils.Auth;
import Utils.ShareHelper;

/**
 *
 * @author dantr
 */
public class PromoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PromoJFrame
     */
    public PromoJFrame() {
        initComponents();
        initModel();
//        fillToTable();
    }

	PromoJFrame(MainJFrame aThis, boolean b) {
		initComponents();
		initModel();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                tabs = new javax.swing.JTabbedPane();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txtIDKhuyenMai = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtTenChuongTrinh = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txtMienGiam = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txtMoTa = new javax.swing.JTextField();
                btnFirst = new javax.swing.JButton();
                btnPrev = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();
                btnLast = new javax.swing.JButton();
                btnMoi = new javax.swing.JButton();
                btnXoa = new javax.swing.JButton();
                btnSua = new javax.swing.JButton();
                btnThem = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblPromo = new javax.swing.JTable();
                btnBack1 = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(255, 255, 255));

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                jLabel2.setBackground(new java.awt.Color(255, 255, 255));
                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel2.setText("Promo ID:");

                txtIDKhuyenMai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 255)));
                txtIDKhuyenMai.setPreferredSize(new java.awt.Dimension(64, 42));

                jLabel3.setBackground(new java.awt.Color(255, 255, 255));
                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel3.setText("Promo Name:");

                txtTenChuongTrinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 255)));
                txtTenChuongTrinh.setPreferredSize(new java.awt.Dimension(64, 42));

                jLabel4.setBackground(new java.awt.Color(255, 255, 255));
                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel4.setText("Discount (%):");

                txtMienGiam.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 255)));
                txtMienGiam.setPreferredSize(new java.awt.Dimension(64, 42));

                jLabel5.setBackground(new java.awt.Color(255, 255, 255));
                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel5.setText("Description:");

                txtMoTa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 255)));
                txtMoTa.setPreferredSize(new java.awt.Dimension(64, 42));

                btnFirst.setBackground(new java.awt.Color(255, 153, 255));
                btnFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnFirst.setForeground(new java.awt.Color(0, 0, 0));
                btnFirst.setText("|<<");
                btnFirst.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnFirstActionPerformed(evt);
                        }
                });

                btnPrev.setBackground(new java.awt.Color(255, 153, 255));
                btnPrev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnPrev.setForeground(new java.awt.Color(0, 0, 0));
                btnPrev.setText("<<");
                btnPrev.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPrevActionPerformed(evt);
                        }
                });

                btnNext.setBackground(new java.awt.Color(255, 153, 255));
                btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnNext.setForeground(new java.awt.Color(0, 0, 0));
                btnNext.setText(">>");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });

                btnLast.setBackground(new java.awt.Color(255, 153, 255));
                btnLast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnLast.setForeground(new java.awt.Color(0, 0, 0));
                btnLast.setText(">>|");
                btnLast.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLastActionPerformed(evt);
                        }
                });

                btnMoi.setBackground(new java.awt.Color(255, 153, 255));
                btnMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnMoi.setForeground(new java.awt.Color(0, 0, 0));
                btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/List (2).png"))); // NOI18N
                btnMoi.setText("New");
                btnMoi.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMoiActionPerformed(evt);
                        }
                });

                btnXoa.setBackground(new java.awt.Color(255, 153, 255));
                btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnXoa.setForeground(new java.awt.Color(0, 0, 0));
                btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
                btnXoa.setText("Delete");
                btnXoa.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnXoaActionPerformed(evt);
                        }
                });

                btnSua.setBackground(new java.awt.Color(255, 153, 255));
                btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnSua.setForeground(new java.awt.Color(0, 0, 0));
                btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
                btnSua.setText("Update");
                btnSua.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSuaActionPerformed(evt);
                        }
                });

                btnThem.setBackground(new java.awt.Color(255, 153, 255));
                btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnThem.setForeground(new java.awt.Color(0, 0, 0));
                btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plus.png"))); // NOI18N
                btnThem.setText("Add");
                btnThem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnThemActionPerformed(evt);
                        }
                });

                btnBack.setBackground(new java.awt.Color(255, 255, 255));
                btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                btnBack.setForeground(new java.awt.Color(255, 102, 255));
                btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Back.png"))); // NOI18N
                btnBack.setText("BACK");
                btnBack.setMaximumSize(new java.awt.Dimension(111, 51));
                btnBack.setMinimumSize(new java.awt.Dimension(111, 51));
                btnBack.setPreferredSize(new java.awt.Dimension(111, 51));
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIDKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTenChuongTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMienGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMoTa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 1191, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIDKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTenChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                tabs.addTab("PROMOTIONS", jPanel2);

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));

                jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

                tblPromo.setBackground(new java.awt.Color(255, 255, 255));
                tblPromo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                tblPromo.setForeground(new java.awt.Color(255, 102, 255));
                tblPromo.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tblPromo.setName(""); // NOI18N
                tblPromo.setRowHeight(35);
                tblPromo.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblPromoMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tblPromo);

                btnBack1.setBackground(new java.awt.Color(255, 255, 255));
                btnBack1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                btnBack1.setForeground(new java.awt.Color(255, 102, 255));
                btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Back.png"))); // NOI18N
                btnBack1.setText("BACK");
                btnBack1.setMaximumSize(new java.awt.Dimension(111, 51));
                btnBack1.setMinimumSize(new java.awt.Dimension(111, 51));
                btnBack1.setPreferredSize(new java.awt.Dimension(111, 51));
                btnBack1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBack1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1359, Short.MAX_VALUE)
                        .addComponent(btnBack1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                tabs.addTab("LIST", jPanel3);

                jLabel1.setBackground(new java.awt.Color(255, 255, 255));
                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 0, 255));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("CHƯƠNG TRÌNH GIẢM GIÁ");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tabs)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabs))
                );

                tabs.getAccessibleContext().setAccessibleParent(tabs);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void tblPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblPromo.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblPromoMouseClicked

        private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
                // TODO add your handling code here:
                first();
        }//GEN-LAST:event_btnFirstActionPerformed

        private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
                // TODO add your handling code here:
                prev();
        }//GEN-LAST:event_btnPrevActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                next();
        }//GEN-LAST:event_btnNextActionPerformed

        private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
                // TODO add your handling code here:
                last();
        }//GEN-LAST:event_btnLastActionPerformed

        private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
                // TODO add your handling code here:
                clearForm();
        }//GEN-LAST:event_btnMoiActionPerformed

        private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
                // TODO add your handling code here:
                delete();
        }//GEN-LAST:event_btnXoaActionPerformed

        private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
                // TODO add your handling code here:
                update();
        }//GEN-LAST:event_btnSuaActionPerformed

        private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
                // TODO add your handling code here:
                insert();
        }//GEN-LAST:event_btnThemActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                btnBack();
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
                // TODO add your handling code here:
		 btnBack();
        }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromoJFrame().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnBack1;
        private javax.swing.JButton btnFirst;
        private javax.swing.JButton btnLast;
        private javax.swing.JButton btnMoi;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnPrev;
        private javax.swing.JButton btnSua;
        private javax.swing.JButton btnThem;
        private javax.swing.JButton btnXoa;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTabbedPane tabs;
        private javax.swing.JTable tblPromo;
        private javax.swing.JTextField txtIDKhuyenMai;
        private javax.swing.JTextField txtMienGiam;
        private javax.swing.JTextField txtMoTa;
        private javax.swing.JTextField txtTenChuongTrinh;
        // End of variables declaration//GEN-END:variables
// khai báo model table
    private DefaultTableModel model;
    PromotionDAO dao = new PromotionDAO();
    int row = -1;

    // set table
    public void initModel() {
        setIconImage(ShareHelper.APP_ICON);
        model = new DefaultTableModel(new Object[0][], (Object[]) new String[]{"IdPromo", "NamePromo", "DiscountPromo", "Description"}) {
            boolean[] canEdit = new boolean[]{false, false, false, false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return this.canEdit[columnIndex];
            }
        };
        tblPromo.setModel(model);
        setLocationRelativeTo(null);
        fillToTable();
        row = -1;
        updateStatus();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	if(!Auth.isAdmin()){
		tabs.remove(0);
	}
    }// set tblPromo

    /// hiện các thuộc tính lên table
    void fillToTable() {
        model = (DefaultTableModel) tblPromo.getModel();
        model.setRowCount(0);
        try {
            List<Promotions> list = dao.selectAll();
            for (Promotions pro : list) {
                Object[] row = {
                    pro.getIdPromo(), pro.getNamePromo(), pro.getDiscountPromo(), pro.getDescription()
                }; // end object
                model.addRow(row);
            }

        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    // các nút điều hướng

    void last() {
        this.row = tblPromo.getRowCount() - 1;
        this.edit();
    }

    void next() {
        if (this.row < tblPromo.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void first() {
        this.row = 0;
        this.edit();
    }

    void edit() {
        String manv = (String) tblPromo.getValueAt(this.row, 0);
        Promotions pro = dao.selectById(manv);
        this.setForm(pro);
        tabs.setSelectedIndex(0);
//        fillToTable();
        this.updateStatus();
    }

    void setForm(Promotions pro) {
        ArrayList<Promotions> list = new ArrayList<>();
//        System.out.println(list);
        txtIDKhuyenMai.setText(pro.getIdPromo());
        txtTenChuongTrinh.setText(pro.getNamePromo());
        txtMienGiam.setText(String.valueOf(pro.getDiscountPromo()));
        txtMoTa.setText(pro.getDescription());
    }

    Promotions getForm() {
        Promotions pro = new Promotions();
        pro.setIdPromo(txtIDKhuyenMai.getText());
        pro.setNamePromo(txtTenChuongTrinh.getText());
        pro.setDiscountPromo(Double.valueOf(txtMienGiam.getText()));
        pro.setDescription(txtMoTa.getText());

        return pro;
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblPromo.getRowCount() - 1);

        txtIDKhuyenMai.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }// hiện trạng thái các button

    void clearForm() {
        txtIDKhuyenMai.setText("");
        txtTenChuongTrinh.setText("");
        txtMienGiam.setText("");
        txtMoTa.setText("");
        txtIDKhuyenMai.requestFocus();
        this.row = -1;
        this.updateStatus();
    }// end clear Form

    // thêm dữ liệu vào database
    void insert() {
        if (valiDate() == true) {

            Promotions pro = getForm();
            try {
                System.out.println(txtIDKhuyenMai.getText());
                dao.insert(pro);
                this.fillToTable();
                this.clearForm();
                MsgBox.alert(this, "INSERT is success!");
            } catch (Exception e) {
                System.out.println(e);
                MsgBox.alert(this, "INSERT is fail!");
            }// end try
        }

    }/// end insert

    void delete() {
        String idPro = txtIDKhuyenMai.getText();
        if (Auth.isAdmin() == true) {
            if (MsgBox.confirm(this, "Are you sure for DELETE?")) {
                try {
                    dao.delete(idPro);
                    this.fillToTable();
                    this.clearForm();
                    MsgBox.alert(this, "DELETE is success!");
                } catch (Exception e) {
                    MsgBox.alert(this, "DELETE is fail!");
                } // try catch
            }// end if
        } else {
            MsgBox.alert(this, "You must login with admin account !");
        }

    }// end delete

    void update() {
        Promotions pro = getForm();
        if (valiDate() == true) {
            try {
                dao.update(pro);
                this.fillToTable();
                MsgBox.alert(this, "UPDATE is success!");
            } catch (Exception e) {
                MsgBox.alert(this, "UPDATE is fail!");
            }// end try
        }

    }// end update

    boolean valiDate() {

        if (txtIDKhuyenMai.getText().isEmpty()) {
            MsgBox.alert(this, "ID can not be empty!");
            return false;
        }
        if (txtTenChuongTrinh.getText().isEmpty()) {
            MsgBox.alert(this, "Program Name can not be empty!");
            return false;
        }
        if (txtMienGiam.getText().matches("[0][0-9]{9}")) {
            MsgBox.alert(this, "WRONG discount format!");
            return false;
        }
        if (txtMoTa.getText().isEmpty()) {
            MsgBox.alert(this, "description Name can not be empty!");
            return false;
        }

        return true;
    }

	private void btnBack() {
		this.dispose();
		new MainJFrame(this, true).setVisible(true);
	}

}// end class
